/*
 * MTIMER1_Config.h
 *
 *  Created on: Feb 15, 2122
 *      Author: Dell
 */

#ifndef MCAL_MTIMER1_MTIMER1_CONFIG_H_
#define MCAL_MTIMER1_MTIMER1_CONFIG_H_

/*Timer 1 CTC Mode PIN OC1A And OC1B Option
 * 1-TIMER1_CTCMODE_TOGGLEOC1A_OC1BPIN
 * 2-TIMER1_CTCMODE_SETOC1A_OC1BPIN
 * 3-TIMER1_CTCMODE_CLROC1A_OC1BPIN
 * 4-TIMER1_CTCMODE_OC1A_OC1BPIN_NOTCONNECTED */

#define TIMER1_CTCMODE_OC1A_OC1BPINMODE  TIMER1_CTCMODE_OC1A_OC1BPIN_NOTCONNECTED

/*TIMER1 Options Mode
 * 1-TIMER1_CTCMODE                                     -->(TOP--<OCR1A)
 * 2-TIMER1_NORMALMODE
 * 3-TIMER1_PWMPHASECOORECT_8_BIT_MODE
 * 4-TIMER1_PWMPHASECOORECT_9_BIT_MODE
 * 5-TIMER1_PWMPHASECOORECT_10_BIT_MODE
 * 6-TIMER1_FASTPWM_8_BIT_MODE
 * 7-TIMER1_FASTPWM_9_BIT_MODE
 * 8-TIMER1_FASTPWM_10_BIT_MODE
 * 9-TIMER1_PWMPHASECOORECT_FREQUENCYCORRECT_MODE_ICR         -->(TOP =ICR1)
 * 10-TIMER1_PWMPHASECOORECT_FREQUENCYCORRECT_MODE_OCR1A      -->(TOP =OCR1A)
 * 11-TIMER1_PWMPHASECOORECT_MODE_ICR                         -->(TOP =ICR1)
 * 12-TIMER1_PWMPHASECOORECT_MODE_OCR1A                       -->(TOP =OCR1A)
 * 13-TIMER1_CTC_MODE                                         -->(TOP = ICR1)
 * 14-TIMER1_FASTPWM_MODE_ICR                                 -->(TOP = ICR1)
 * 15-TIMER1_FASTPWM_MODE_OCR1A                               -->(TOP =OCR1A)
 * */
#define TIMER1SETMODE  TIMER1_FASTPWM_MODE_OCR1A

/* PWM MODE OC1A And OC1B Pin mode
 * 1-TIMER1_PWMMODE_NON_INVERTING   -->(CLR OC1A And OC1B On Compare Match and Set OC1A And OC1B At Top)(CLR OC0-->upcount )
 * 2-TIMER1_PWMMODE_INVERTING       -->(SET OC1A And OC1B On Compare Match and OC1A And OC1B At Top) (SET OC0-->upcount )*/

#define TIMER1_PWMMODE_OC1A_OC1B_PINMODE  TIMER1_PWMMODE_NON_INVERTING

/*TIMER1 PreScaler Options
 * 1-TIMER1_NOPRESCALER
 * 2-TIMER1_PRESCALER_8
 * 3-TIMER1_PRESCALER_64
 * 4-TIMER1_PRESCALER_256
 * 5-TIMER1_PRESCALER_1024
 * 6-TIMER1_EXTRERNALCLOCK_FALLINGEDGE
 * 7-TIMER1_EXTRERNALCLOCK_RISINGEDGE
 * */
#define  TIMER1_SETPRESCALER  TIMER1_PRESCALER_8

#endif /* MCAL_MTIMER1_MTIMER1_CONFIG_H_ */
