/*
 * HCLCD_Config.h
 *
 *
 */

#ifndef HAL_HCLCD_HCLCD_CONFIG_H_
#define HAL_HCLCD_HCLCD_CONFIG_H_

/*Control Port Options:
 * 1- MDIO_PORTA
 * 2- MDIO_PORTB
 * 3- MDIO_PORTC
 * 4- MDIO_PORTD*/

#define HCLCD_ControlPort  MDIO_PORTA

/*Control Pins Options:
 * PIN0:PIN7
 */
#define RS_PIN     PIN1
#define RW_PIN     PIN2
#define E_PIN      PIN3

/*Data Port Options:
 * 1- MDIO_PORTA
 * 2- MDIO_PORTB
 * 3- MDIO_PORTC
 * 4- MDIO_PORTD*/
#define HCLCD_DataPort   MDIO_PORTA

/*Function set Options:
 * 1- FUNCTIONSET_4BITMODE_2LINES
 * 2- FUNCTIONSET_4BITMODE_1LINES
 * 3- FUNCTIONSET_8BITMODE_2LINES
 * 4- FUNCTIONSET_8BITMODE_1LINES
 */
#define SET_FUNCTIONSET   FUNCTIONSET_4BITMODE_2LINES

/*Display On/Off Options:
 * 1- DISPLAYON_CURSORON_BLINKING
 * 2- DISPLAYON_CURSORON_NOBLINKING
 * 3- DISPLAYON_CURSOROFF
 * 4- DISPLAYOFF
 */
#define SET_DISPLAYON_OFF   DISPLAYON_CURSORON_BLINKING

#define SET_DISPALYCLEAR     DISPLAY_CLEAR

/*Entry Mode Options:
 * 1- ENTRYMODE_INCREASE_SHIFT
 * 2- ENTRYMODE_INCREASE_NOSHIFT
 * 3- ENTRYMODE_DECREASE_SHIFT
 * 4- ENTRYMODE_DECREASE_NOSHIFT
 */
#define SET_ENTRYMODE    ENTRYMODE_INCREASE_NOSHIFT

#endif /* HAL_HCLCD_HCLCD_CONFIG_H_ */
